baseURL = "http://fogjoe.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "zh-cn"
# language code
languageCode = "zh-cn"
theme = "LoveIt"
title = "Joe's Blog"
enableRobotsTXT = true       # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
rssLimit = 20                # limit number of entries in RSS feeds

disablePathToLower = true 
defaultContentLanguageInSubdir = false

# Syntax Hightlight
PygmentsCodeFences = true
PygmentsUseClasses = true    # required for shhighlight shortcode

paginate = 20
paginatePath = "page"

[author]
  name = 'Joe'
  email = 'fogjoe77@gmail.com'

[params]
  since = "2024"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  description = "Welcome to the real world, it sucks, but you gonna love it!"

  [params.header]
    [params.header.title]
      logo = "/images/fogjoe-transparent.png"
      name = ""

  [params.author]
    [params.author.name]
      name = "Joe"
    [params.author.email]
      email = "fogjoe77@gmail.com"

  [params.app]  
    title = "Joe's Blog"
  [params.home]
    [params.home.profile]
      subtitle= "Welcome to the real world, it sucks, but you gonna love it!"
  
[menu]
  [[menu.main]]
    identifier = "sports"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "运动"
    url = "/sports/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "life"
    name = "生活"
    url = "/life/"
    weight = 3
  [[menu.main]]
    identifier = "posts"
    name = "技术"
    url = "/posts/"
    pre = ""
    post = ""
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 5

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
