baseURL = "http://fogjoe.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "zh-cn"
# language code
languageCode = "zh-cn"
theme = "LoveIt"
title = "Joe's Blog"
enableRobotsTXT = true       # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
rssLimit = 20                # limit number of entries in RSS feeds

disablePathToLower = true 
defaultContentLanguageInSubdir = false

# Syntax Hightlight
PygmentsCodeFences = true
PygmentsUseClasses = true    # required for shhighlight shortcode

paginate = 20
paginatePath = "page"

[author]
  name = 'Joe'
  email = 'fogjoe77@gmail.com'

[params]
  since = "2024"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  description = "Welcome to the real world, it sucks, but you gonna love it!"

  [params.page]
    hiddenFromSearch = false

  [params.header]
    [params.header.title]
      logo = "/images/fogjoe-transparent.png"
      name = ""

  [params.author]
    [params.author.name]
      name = "Joe"
    [params.author.email]
      email = "fogjoe77@gmail.com"

  [params.app]  
    title = "Joe's Blog"
  [params.home]
    [params.home.profile]
      subtitle= "Welcome to the real world, it sucks, but you gonna love it!"
    [params.home.posts]
      enable = false
      paginate = 6
      defaultHiddenFromHomePage = false

  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 50
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      # index = "index"
      # appID = "PASDMWALPK"
      # searchKey = "b42948e51daaa93df92381c8e2ac0f93"
      index = ""
      appID = ""
      searchKey = ""
  
[menu]
  # [[menu.main]]
  #   identifier = "sports"
  #   # you can add extra information before the name (HTML format is supported), such as icons
  #   pre = ""
  #   # you can add extra information after the name (HTML format is supported), such as icons
  #   post = ""
  #   name = "运动"
  #   url = "/sports/"
  #   # title will be shown when you hover on this menu link
  #   title = ""
  #   weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 3
  # [[menu.main]]
  #   identifier = "life"
  #   name = "生活"
  #   url = "/life/"
  #   weight = 3
  # [[menu.main]]
  #   identifier = "books"
  #   name = "阅读"
  #   url = "/books/"
  #   weight = 6
  # [[menu.main]]
  #   identifier = "essay"
  #   name = "随笔"
  #   url = "/essay/"
  #   weight = 7

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
