baseURL = "http://fogjoe.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "zh-cn"
# language code
languageCode = "zh-cn"
title = "Joe's Blog"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  title ="Joe's Blog111"
  description = "Welcome to the real world, it sucks, but you gonna love it!"

  [params.header]
    [params.header.title]
      name = "Joe's Blog"

  [params.author]
    [params.author.name]
      name = "Joe"
    [params.author.email]
      email = "fogjoe77@gmail.com"

  [params.app]  
    title = "Joe's Blog"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "技术"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "生活"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "随笔"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
